import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  AccountType,
  getPythClusterApiUrl,
  getPythProgramKeyForCluster,
  parseBaseData,
  parsePriceData,
  parseProductData,
  type PythCluster,
} from '@pythnetwork/client'
import { Connection } from '@solana/web3.js'

type Category = (typeof ASSET_PREFIXES)[number]['category']

const CLUSTER: PythCluster = 'pythnet'
const __dirname = path.dirname(fileURLToPath(import.meta.url))

const ASSET_PREFIXES = [
  { prefix: 'Crypto.', category: 'crypto' as const },
  { prefix: 'Equity.', category: 'equities' as const },
  { prefix: 'Metal.', category: 'commodities' as const },
  { prefix: 'Commodities.', category: 'commodities' as const },
  { prefix: 'FX.', category: 'forex' as const },
  { prefix: 'Rates.', category: 'rates' as const },
] as const

const CATEGORY_EXPORT_NAMES: Record<Category, string> = {
  crypto: 'PYTH_CRYPTO_FEEDS',
  equities: 'PYTH_EQUITIES_FEEDS',
  commodities: 'PYTH_COMMODITIES_FEEDS',
  forex: 'PYTH_FOREX_FEEDS',
  rates: 'PYTH_RATES_FEEDS',
}

function categorizeSymbol(symbol: string): Category | null {
  for (const { prefix, category } of ASSET_PREFIXES) {
    if (symbol.startsWith(prefix)) {
      return category
    }
  }

  return null
}

function normalizeKey(symbol: string, _category: Category): string {
  let rest = symbol

  for (const { prefix } of ASSET_PREFIXES) {
    if (rest.startsWith(prefix)) {
      rest = rest.slice(prefix.length)
      break
    }
  }

  return rest
    .replace(/[./\s-]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase()
    .replace(/\*+/g, 'X') // e.g. USD* -> USDX for valid identifier
}

function formatKey(key: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `"${key}"`
}

async function main() {
  const connection = new Connection(getPythClusterApiUrl(CLUSTER))
  const programKey = getPythProgramKeyForCluster(CLUSTER)

  console.log('Loading Pyth accounts...')

  const [accountList, currentSlot] = await Promise.all([
    connection.getProgramAccounts(programKey, 'confirmed'),
    connection.getSlot('confirmed'),
  ])

  const productAccountKeyToProduct = new Map<string, { symbol: string }>()

  for (const { pubkey, account } of accountList) {
    const base = parseBaseData(account.data)

    if (!base) {
      continue
    }

    switch (base.type) {
      case AccountType.Product: {
        const productData = parseProductData(account.data)
        const symbol = productData.product?.symbol ?? productData.product?.asset_type

        if (symbol) {
          productAccountKeyToProduct.set(pubkey.toBase58(), { symbol })
        }

        break
      }
      default:
        break
    }
  }

  const feeds: { symbol: string; priceKey: string }[] = []

  for (const { pubkey, account } of accountList) {
    const base = parseBaseData(account.data)

    if (!base || base.type !== AccountType.Price) {
      continue
    }

    const priceData = parsePriceData(account.data, currentSlot)
    const product = productAccountKeyToProduct.get(priceData.productAccountKey.toBase58())

    if (!product?.symbol) {
      continue
    }

    feeds.push({
      symbol: product.symbol,
      priceKey: pubkey.toBase58(),
    })
  }

  const categorized = new Map<Category, { key: string; symbol: string; priceKey: string }[]>()

  for (const feed of feeds) {
    const category = categorizeSymbol(feed.symbol)

    if (!category) {
      continue
    }

    const key = normalizeKey(feed.symbol, category)

    if (!key) {
      continue
    }

    const list = categorized.get(category) ?? []
    const existing = list.find((x) => x.key === key)

    if (existing) {
      continue
    }

    list.push({ key, symbol: feed.symbol, priceKey: feed.priceKey })
    categorized.set(category, list)
  }

  const outputDir = path.join(__dirname, '../lib/pyth-feeds')
  await fs.mkdir(outputDir, { recursive: true })

  const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: pnpm run generate:feeds
 * @see https://pyth.network/developers/price-feed-ids
 */`

  for (const [category, items] of categorized) {
    items.sort((a, b) => a.key.localeCompare(b.key))
    const exportName = CATEGORY_EXPORT_NAMES[category]
    const lines = items
      .map((f) => `  ${formatKey(f.key)}: new PublicKey("${f.priceKey}"),`)
      .join('\n')

    const content = `${header}

import { PublicKey } from '@solana/web3.js'

export const ${exportName} = {
${lines}
} as const
`

    const filename = `${category}.ts`
    const filepath = path.join(outputDir, filename)
    await fs.writeFile(filepath, content)
    console.log(`  ${filename}: ${items.length} feeds`)
  }

  const indexExports = Array.from(categorized.keys())
    .sort()
    .map((category) => `export * from './${category}'`)
    .join('\n')

  const indexContent = `${header}

${indexExports}
`

  await fs.writeFile(path.join(outputDir, 'index.ts'), indexContent)
  console.log(`  index.ts: re-exports ${categorized.size} categories`)

  const total = Array.from(categorized.values()).reduce((sum, arr) => sum + arr.length, 0)
  console.log(`\nGenerated ${total} feeds -> ${outputDir}`)
}

main().catch(console.error)
