/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: pnpm run generate:feeds
 * @see https://pyth.network/developers/price-feed-ids
 */

import { PublicKey } from '@solana/web3.js'

export const PYTH_RATES_FEEDS = {
  BGCR: new PublicKey('9y7eoCH9HtuTqMu59tXAMfMbpCwDqRoR3F5UQr8o5vn3'),
  EFFR: new PublicKey('9JL4fyMNmwcaexCPWmwiq3DRW6rZCHRcsfnagSga7spD'),
  EPE_USDC: new PublicKey('DhK8mRa625MXDRvoHjPm5cCjcfzsCzgGcwCYWAANvsGY'),
  EYE_USDC: new PublicKey('HDTnHRG7xvRWLYsfDZR3cHYN3DwuquxtPrajfjPkCa3a'),
  OBFR: new PublicKey('Cp8szn592PbNwN7nPeizewK3s5ke7SzpB2ixDLT9jwU1'),
  SOFR: new PublicKey('231sX1Gg4zkbMpHfuqqMKjkyZavGnw6qmvypUvkAgvjg'),
  TGCR: new PublicKey('5RZKJax7qQNit8agcdnRbu9FvRneygFbNnfd8aaGsmpE'),
  US10Y: new PublicKey('BWM4XUHeb4YhpbtpNfGMx2t4aAPPmhTqHBnT7GfCWmSp'),
  US10Y_USD: new PublicKey('AcR9d6ayzrcM7bcb3UJAFZWZ5kvkaMjrtwj9NDqUMfVb'),
  US1M: new PublicKey('7TriS92q4rR9bbjo3Sw5fWvnbQ4LMGCDWRuArA9SA28q'),
  US1Y: new PublicKey('H5YM678ER9zLJrPe5BjDdpTqiLuwy7Wbo3vQWUWR3kRy'),
  US1Y_USD: new PublicKey('7wkbNywq42XxSpYPQAUQv6AJWaJEJLKwkRVa5d83hveT'),
  US20Y: new PublicKey('FhKaXHQ8DczxmjhkJAhD6nijrd3TYqyNx1TisiLzT6Dq'),
  US20Y_USD: new PublicKey('4fJbZndMejzQhAVq1WLa6iZi4yx1qLQYDU3RfBXq18Z1'),
  US2Y: new PublicKey('9QyfQLCDkoubb71bAG5yaMtYq42PsBj6UGQCKN2bNmAh'),
  US2Y_USD: new PublicKey('HLX1Pea5Vgd5UGHd72MRQuDyVu8KFGYnDfaCPto3KEcJ'),
  US30Y: new PublicKey('5ToVHCXnp9sZ6aAfDVaSU3B86N6HN16Zy4hdKvEEN5y7'),
  US30Y_USD: new PublicKey('EujRzPjF926DAGFLxdki71zsxMyrYDLQqkuaYty5YFyU'),
  US3M: new PublicKey('7Q6uuWMvzwGwSBCzyxih5ERuLPWnG73sV8pwMBjnREne'),
  US3Y: new PublicKey('3Y4Q55jxA6uxbT6GFGDXpJC6QZxk5irKLGgYqgQeZCjD'),
  US3Y_USD: new PublicKey('8Spo1hZE5YG2kCz2rAjiRvSdmon9zaNe3n3L4z1TjqwE'),
  US5Y: new PublicKey('9RU54pyDq8c3U37pF45E2mSY6pLUagHTQ3CXkC92Gf2u'),
  US5Y_USD: new PublicKey('54vLHDqp44Xh1RePktgsJ6FbaKyp41hiSF1i3Pd1AASP'),
  US6M: new PublicKey('3RYXgAFatoHnVPE1Aduv8Dr4yJJEUB87jhdnWpJ6qRto'),
  US7Y: new PublicKey('3Bz1YGbtJNMzZHANu5JENvZ67A4bjHjmmGYMVVwadpSR'),
  US7Y_USD: new PublicKey('9uJbQPfRwhnBhrqysN3iwp1QMnPcDhbBAohxPBJtdyUu'),
} as const
